hide: true

fields:
  
  _template:    
    default: default
    type: templates
    hide: true
    
  slug:
    hide: true
    
  content:
    type: hidden

  _seo:
    type: section
    display: SEO Keywords / Phrases
    instructions: Enter a comma (,) separated list of words / phrases, that if typed into a Search Engine (eg. Google Search) should take you to this page.

  seo:
    type: textarea
    display: Keywords / Phrases